import React, { useState, useEffect } from 'react'
import {
  Sparkles,
  MapPin,
  DollarSign,
  Compass,
  CloudSun,
  Utensils,
  Calendar,
  FileText,
  Copy,
  Check,
  Download,
  ArrowRight,
  RefreshCw,
  Cpu,
  AlertCircle,
  ExternalLink,
  ChevronRight
} from 'lucide-react'
import { travelBuddyService } from '../services/api'

export default function TravelBuddyAgent({ onSelectPlan }) {
  const [city, setCity] = useState('Goa')
  const [budget, setBudget] = useState('15000')
  const [currency, setCurrency] = useState('INR')
  const [travelStyle, setTravelStyle] = useState('explorer')

  const [loading, setLoading] = useState(false)
  const [currentStep, setCurrentStep] = useState(0)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [activeTab, setActiveTab] = useState('preview') // 'preview' | 'markdown' | 'reasoning'
  const [copied, setCopied] = useState(false)

  const quickCities = ['Goa', 'Mumbai', 'Bangalore', 'Paris', 'Tokyo', 'Jaipur', 'Manali', 'London']

  const currencySymbols = {
    INR: '₹',
    USD: '$',
    EUR: '€',
    GBP: '£'
  }

  const travelStyles = [
    { id: 'explorer', label: 'Explorer', icon: '🧭' },
    { id: 'foodie', label: 'Foodie', icon: '🍜' },
    { id: 'relaxed', label: 'Relaxed', icon: '🌴' },
    { id: 'adventure', label: 'Adventure', icon: '🧗' }
  ]

  const executionStepLabels = [
    { title: 'Agent Planning', desc: 'Formulating search parameters & budget constraints' },
    { title: 'Weather Forecaster Tool', desc: 'Querying live 7-day atmospheric forecast & packing needs' },
    { title: 'Restaurant Finder Tool', desc: 'Locating top 3 affordable dining spots within budget limit' },
    { title: 'Event Radar Tool', desc: 'Scouting local festivals, markets, and happenings this week' },
    { title: 'LangChain Synthesis', desc: 'Compiling structured Markdown travel guide document' }
  ]

  const handleRunAgent = async (e) => {
    if (e) e.preventDefault()
    if (!city.trim()) {
      setError('Please enter a destination city.')
      return
    }

    setLoading(true)
    setError(null)
    setCurrentStep(0)
    setResult(null)

    // Simulate animated step progression
    const stepInterval = setInterval(() => {
      setCurrentStep((prev) => {
        if (prev < 4) return prev + 1
        return prev
      })
    }, 600)

    try {
      const data = await travelBuddyService.generateGuide(
        city.trim(),
        parseFloat(budget) || 10000,
        currency,
        travelStyle
      )
      clearInterval(stepInterval)
      setCurrentStep(4)
      setResult(data)
    } catch (err) {
      clearInterval(stepInterval)
      console.error('Agent Execution Failed:', err)
      setError(
        err.response?.data?.detail ||
          'Failed to execute Travel Buddy Agent. Please check your connection and try again.'
      )
    } finally {
      setLoading(false)
    }
  }

  const handleCopyMarkdown = () => {
    if (!result?.markdown) return
    navigator.clipboard.writeText(result.markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const handleDownloadMarkdown = () => {
    if (!result?.markdown) return
    const blob = new Blob([result.markdown], { type: 'text/markdown;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `travel-buddy-${city.toLowerCase().replace(/\s+/g, '-')}-guide.md`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const handleBookWithPlan = () => {
    if (!result?.data?.booking_details) return

    const bookingDetails = result.data.booking_details
    const aiSuggestion = {
      id: `ai_${city.toLowerCase()}`,
      title: `${city.toUpperCase()} ${travelStyle.toUpperCase()} TRIP`,
      desc: `Generated by Voyago Travel Buddy Agent`,
      price: `${currencySymbols[currency] || '₹'}${budget}`,
      itinerary: result.markdown,
      details: bookingDetails
    }

    if (onSelectPlan) {
      onSelectPlan(aiSuggestion)
    }
  }

  return (
    <div className="bg-gradient-to-br from-gray-900 via-purple-950 to-indigo-950 rounded-3xl p-6 md:p-8 text-white mb-8 border border-purple-500/40 shadow-2xl relative overflow-hidden">
      {/* Ambient background glows */}
      <div className="absolute top-0 right-0 -mr-24 -mt-24 w-96 h-96 bg-purple-600 rounded-full mix-blend-screen filter blur-3xl opacity-20 pointer-events-none animate-pulse"></div>
      <div className="absolute bottom-0 left-0 -ml-24 -mb-24 w-96 h-96 bg-indigo-600 rounded-full mix-blend-screen filter blur-3xl opacity-20 pointer-events-none"></div>

      <div className="relative z-10">
        {/* Header Badge & Title */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
          <div className="flex items-center space-x-3">
            <span className="bg-purple-500/20 text-purple-300 text-xs md:text-sm font-semibold px-3.5 py-1.5 rounded-full border border-purple-400/40 flex items-center shadow-inner">
              <Sparkles className="w-4 h-4 text-purple-400 mr-2 animate-spin" style={{ animationDuration: '4s' }} />
              AUTONOMOUS TRAVEL BUDDY AGENT • POWERED BY LANGCHAIN
            </span>
          </div>

          <div className="flex items-center space-x-2 text-xs text-purple-200 bg-white/5 px-3 py-1.5 rounded-full border border-white/10">
            <Cpu className="w-3.5 h-3.5 text-green-400" />
            <span>Autonomous Tool Coordination (Weather, Dining & Events)</span>
          </div>
        </div>

        <div className="max-w-3xl mb-8">
          <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight mb-3 bg-gradient-to-r from-white via-purple-100 to-pink-200 bg-clip-text text-transparent">
            The Travel Buddy Agent
          </h1>
          <p className="text-purple-200 text-sm md:text-base leading-relaxed">
            Enter a destination city and budget. Our LangChain agent autonomously scouts the{' '}
            <strong className="text-white">top 3 affordable restaurants</strong>,{' '}
            <strong className="text-white">live 7-day weather forecast</strong>, and{' '}
            <strong className="text-white">local events happening this week</strong> — compiling everything into a clean,
            publication-grade Markdown document.
          </p>
        </div>

        {/* Search & Configuration Form */}
        <form onSubmit={handleRunAgent} className="bg-black/40 backdrop-blur-xl rounded-2xl p-5 md:p-6 border border-purple-500/30 shadow-xl mb-8">
          <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-end">
            {/* City Input */}
            <div className="md:col-span-5">
              <label className="block text-xs font-semibold text-purple-200 uppercase tracking-wider mb-2 flex items-center">
                <MapPin className="w-3.5 h-3.5 mr-1 text-purple-400" /> Destination City
              </label>
              <div className="relative">
                <input
                  type="text"
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  placeholder="e.g. Goa, Paris, Tokyo, Mumbai..."
                  className="w-full bg-white/10 border border-purple-400/30 rounded-xl px-4 py-3 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-base"
                  required
                />
              </div>

              {/* Quick City Chips */}
              <div className="flex flex-wrap gap-1.5 mt-2.5">
                <span className="text-[11px] text-gray-400 py-0.5">Quick pick:</span>
                {quickCities.map((qc) => (
                  <button
                    key={qc}
                    type="button"
                    onClick={() => setCity(qc)}
                    className={`text-xs px-2.5 py-0.5 rounded-full transition-all ${
                      city.toLowerCase() === qc.toLowerCase()
                        ? 'bg-purple-500 text-white font-medium shadow-sm'
                        : 'bg-white/5 text-gray-300 hover:bg-white/15 hover:text-white'
                    }`}
                  >
                    {qc}
                  </button>
                ))}
              </div>
            </div>

            {/* Budget Input & Currency */}
            <div className="md:col-span-4">
              <label className="block text-xs font-semibold text-purple-200 uppercase tracking-wider mb-2 flex items-center">
                <DollarSign className="w-3.5 h-3.5 mr-1 text-green-400" /> Total Budget
              </label>
              <div className="flex rounded-xl overflow-hidden border border-purple-400/30 focus-within:ring-2 focus-within:ring-purple-400">
                <select
                  value={currency}
                  onChange={(e) => setCurrency(e.target.value)}
                  aria-label="Currency"
                  className="bg-purple-900/60 text-purple-200 px-3 py-3 text-sm font-semibold border-r border-purple-400/30 focus:outline-none cursor-pointer"
                >
                  <option value="INR">₹ INR</option>
                  <option value="USD">$ USD</option>
                  <option value="EUR">€ EUR</option>
                  <option value="GBP">£ GBP</option>
                </select>
                <input
                  type="number"
                  value={budget}
                  onChange={(e) => setBudget(e.target.value)}
                  placeholder="15000"
                  min="500"
                  step="500"
                  className="w-full bg-white/10 px-4 py-3 text-white placeholder-gray-400 focus:outline-none text-base"
                  required
                />
              </div>

              {/* Quick Budget Presets */}
              <div className="flex gap-2 mt-2.5">
                {[
                  { label: 'Budget Saver', val: currency === 'INR' ? '6000' : '300' },
                  { label: 'Explorer', val: currency === 'INR' ? '15000' : '750' },
                  { label: 'Comfort', val: currency === 'INR' ? '30000' : '1500' }
                ].map((b) => (
                  <button
                    key={b.label}
                    type="button"
                    onClick={() => setBudget(b.val)}
                    className="text-[11px] bg-white/5 hover:bg-white/15 text-purple-200 px-2 py-0.5 rounded transition-colors"
                  >
                    {b.label} ({currencySymbols[currency]}{b.val})
                  </button>
                ))}
              </div>
            </div>

            {/* Travel Vibe Selector */}
            <div className="md:col-span-3">
              <label className="block text-xs font-semibold text-purple-200 uppercase tracking-wider mb-2 flex items-center">
                <Compass className="w-3.5 h-3.5 mr-1 text-pink-400" /> Travel Vibe
              </label>
              <div className="grid grid-cols-2 gap-1.5">
                {travelStyles.map((style) => (
                  <button
                    key={style.id}
                    type="button"
                    onClick={() => setTravelStyle(style.id)}
                    className={`py-2 px-2 rounded-lg text-xs font-medium flex items-center justify-center transition-all border ${
                      travelStyle === style.id
                        ? 'bg-purple-600/60 border-purple-400 text-white shadow-md'
                        : 'bg-white/5 border-white/5 text-gray-300 hover:bg-white/10'
                    }`}
                  >
                    <span className="mr-1.5">{style.icon}</span> {style.label}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Submit Button */}
          <div className="mt-5 pt-4 border-t border-white/10 flex flex-col sm:flex-row justify-between items-center gap-3">
            <p className="text-xs text-gray-400 flex items-center">
              <span className="w-2 h-2 rounded-full bg-green-400 mr-2"></span>
              Live Autonomous Execution • Open-Meteo Weather • Budget Adherence
            </p>

            <button
              type="submit"
              disabled={loading}
              className={`w-full sm:w-auto px-8 py-3.5 rounded-xl font-bold text-sm md:text-base flex items-center justify-center transition-all shadow-lg ${
                loading
                  ? 'bg-purple-800 text-purple-300 cursor-not-allowed'
                  : 'bg-gradient-to-r from-pink-500 via-purple-600 to-indigo-600 hover:from-pink-400 hover:via-purple-500 hover:to-indigo-500 text-white shadow-purple-500/25 hover:shadow-purple-500/40 transform hover:-translate-y-0.5'
              }`}
            >
              {loading ? (
                <>
                  <RefreshCw className="w-5 h-5 mr-2.5 animate-spin" />
                  Running Agent Chain...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5 mr-2.5" />
                  Run Travel Buddy Agent
                </>
              )}
            </button>
          </div>
        </form>

        {/* Error Alert */}
        {error && (
          <div className="mb-6 p-4 rounded-xl bg-red-950/60 border border-red-500/40 text-red-200 flex items-center space-x-3 text-sm">
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {/* Real-time Agent Step Visualizer */}
        {loading && (
          <div className="bg-black/50 backdrop-blur-md rounded-2xl p-6 border border-purple-500/30 shadow-2xl mb-8 animate-in fade-in duration-300">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <span className="w-3 h-3 bg-purple-400 rounded-full animate-ping"></span>
                <h2 className="font-bold text-base text-purple-200">
                  LangChain Agent Autonomous Execution Trace
                </h2>
              </div>
              <span className="text-xs text-gray-400">Step {currentStep + 1} of 5</span>
            </div>

            <div className="space-y-3">
              {executionStepLabels.map((step, idx) => {
                const isCurrent = currentStep === idx
                const isDone = currentStep > idx
                return (
                  <div
                    key={step.title}
                    className={`p-3.5 rounded-xl border flex items-center justify-between transition-all ${
                      isCurrent
                        ? 'bg-purple-900/40 border-purple-400 text-white shadow-lg'
                        : isDone
                        ? 'bg-green-950/20 border-green-500/30 text-green-200'
                        : 'bg-white/5 border-white/5 text-gray-400 opacity-60'
                    }`}
                  >
                    <div className="flex items-center space-x-3">
                      <div
                        className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold ${
                          isDone
                            ? 'bg-green-500/20 text-green-400 border border-green-500/40'
                            : isCurrent
                            ? 'bg-purple-500 text-white animate-pulse'
                            : 'bg-gray-800 text-gray-400'
                        }`}
                      >
                        {isDone ? <Check className="w-4 h-4" /> : idx + 1}
                      </div>
                      <div>
                        <h3 className="font-semibold text-sm">{step.title}</h3>
                        <p className="text-xs opacity-80">{step.desc}</p>
                      </div>
                    </div>

                    <div>
                      {isCurrent && <RefreshCw className="w-4 h-4 text-purple-300 animate-spin" />}
                      {isDone && <span className="text-xs font-semibold text-green-400">Done</span>}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Results Hub */}
        {result && (
          <div className="bg-black/60 backdrop-blur-xl rounded-2xl border border-purple-500/40 shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Top Toolbar */}
            <div className="p-4 md:p-6 bg-purple-950/40 border-b border-purple-500/30 flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="flex items-center space-x-3">
                <div className="p-2.5 rounded-xl bg-purple-500/20 border border-purple-400/40 text-purple-300">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <div className="flex items-center space-x-2">
                    <h2 className="font-bold text-lg md:text-xl text-white">
                      {city.toUpperCase()} Travel Guide Document
                    </h2>
                    <span className="bg-green-500/20 text-green-300 text-xs px-2.5 py-0.5 rounded-full border border-green-500/40 font-medium">
                      Markdown Ready
                    </span>
                  </div>
                  <p className="text-xs text-gray-400">
                    Budget Target: {currencySymbols[currency] || '₹'}
                    {parseFloat(budget).toLocaleString()} • {travelStyle.toUpperCase()}
                  </p>
                </div>
              </div>

              {/* Action Toolbar */}
              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopyMarkdown}
                  className="px-3.5 py-2 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-semibold flex items-center transition-all border border-white/10"
                  title="Copy Raw Markdown Document"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4 mr-1.5 text-green-400" />
                      <span className="text-green-300">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 mr-1.5 text-purple-300" />
                      Copy Markdown
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={handleDownloadMarkdown}
                  className="px-3.5 py-2 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-semibold flex items-center transition-all border border-white/10"
                  title="Download .md Document"
                >
                  <Download className="w-4 h-4 mr-1.5 text-purple-300" />
                  Download .md
                </button>

                {onSelectPlan && (
                  <button
                    type="button"
                    onClick={handleBookWithPlan}
                    className="px-4 py-2 rounded-lg bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-400 hover:to-emerald-500 text-white text-xs font-bold flex items-center shadow-lg shadow-green-500/20 transition-all transform hover:scale-105"
                  >
                    Plan Vacation with This Itinerary
                    <ArrowRight className="w-4 h-4 ml-1.5" />
                  </button>
                )}
              </div>
            </div>

            {/* Navigation Tabs */}
            <div className="flex border-b border-white/10 px-4 md:px-6 bg-black/30">
              {[
                { id: 'preview', label: 'Formatted Travel Guide', icon: FileText },
                { id: 'markdown', label: 'Markdown Document', icon: FileText },
                { id: 'reasoning', label: 'Agent Reasoning Steps', icon: Cpu }
              ].map((tab) => {
                const Icon = tab.icon
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`py-3 px-4 text-xs md:text-sm font-semibold flex items-center border-b-2 transition-all ${
                      activeTab === tab.id
                        ? 'border-purple-400 text-purple-300 bg-purple-500/10'
                        : 'border-transparent text-gray-400 hover:text-gray-200'
                    }`}
                  >
                    <Icon className="w-4 h-4 mr-2" />
                    {tab.label}
                  </button>
                )
              })}
            </div>

            {/* Tab Contents */}
            <div className="p-5 md:p-8 max-h-[700px] overflow-y-auto custom-scrollbar">
              {/* TAB 1: Visual Formatted Guide */}
              {activeTab === 'preview' && (
                <div className="space-y-8">
                  {/* Weather Highlight */}
                  {result.data?.weather && (
                    <div className="bg-gradient-to-r from-blue-950/40 via-indigo-950/40 to-purple-950/40 rounded-2xl p-5 border border-blue-500/30">
                      <div className="flex items-center space-x-2 mb-3">
                        <CloudSun className="w-5 h-5 text-blue-400" />
                        <h3 className="font-bold text-lg text-white">
                          7-Day Live Weather Outlook & Packing
                        </h3>
                        <span className="text-xs bg-blue-500/20 text-blue-300 px-2 py-0.5 rounded border border-blue-500/40">
                          {result.data.weather.avg_temp} Avg
                        </span>
                      </div>
                      <p className="text-xs md:text-sm text-gray-300 mb-4">
                        {result.data.weather.forecast_summary}
                      </p>

                      {/* Daily Weather Cards */}
                      <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5 mb-4">
                        {result.data.weather.daily_forecast?.map((df, i) => (
                          <div
                            key={i}
                            className="bg-black/40 rounded-xl p-3 text-center border border-white/5"
                          >
                            <span className="text-xl block mb-1">{df.emoji}</span>
                            <div className="text-xs font-bold text-white">{df.date.split(',')[0]}</div>
                            <div className="text-[11px] text-gray-400">{df.condition}</div>
                            <div className="text-xs font-semibold text-blue-300 mt-1">
                              {df.temp_max}° / {df.temp_min}°C
                            </div>
                            {df.precip_chance > 0 && (
                              <div className="text-[10px] text-cyan-400">{df.precip_chance}% rain</div>
                            )}
                          </div>
                        ))}
                      </div>

                      {/* Packing advice */}
                      {result.data.weather.packing_tips && (
                        <div className="bg-black/30 rounded-xl p-3 border border-white/5">
                          <span className="text-xs font-bold text-purple-200 block mb-1.5">
                            🎒 Recommended Packing Essentials:
                          </span>
                          <div className="flex flex-wrap gap-2">
                            {result.data.weather.packing_tips.map((tip, i) => (
                              <span
                                key={i}
                                className="text-xs bg-purple-500/15 text-purple-200 px-2.5 py-1 rounded-full border border-purple-500/30"
                              >
                                ✓ {tip}
                              </span>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {/* Top 3 Affordable Restaurants */}
                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center space-x-2">
                        <Utensils className="w-5 h-5 text-amber-400" />
                        <h3 className="font-bold text-lg md:text-xl text-white">
                          Top 3 Affordable & Delicious Restaurants
                        </h3>
                      </div>
                      <span className="text-xs text-amber-300 bg-amber-500/10 px-2.5 py-1 rounded-full border border-amber-500/30">
                        Strictly Budget Aligned
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      {result.data?.restaurants?.map((r, i) => (
                        <div
                          key={i}
                          className="bg-black/40 rounded-2xl p-4 border border-amber-500/20 hover:border-amber-500/50 transition-all flex flex-col justify-between"
                        >
                          <div>
                            <div className="flex justify-between items-start mb-2">
                              <span className="w-6 h-6 rounded-full bg-amber-500/20 text-amber-300 text-xs font-bold flex items-center justify-center border border-amber-500/40">
                                {i + 1}
                              </span>
                              <span className="text-xs bg-green-500/20 text-green-300 font-bold px-2 py-0.5 rounded border border-green-500/30">
                                {r.price_for_two}
                              </span>
                            </div>

                            <h4 className="font-bold text-base text-white mb-1">{r.name}</h4>
                            <p className="text-xs text-amber-200 font-medium mb-2">{r.cuisine}</p>

                            <div className="text-xs text-gray-300 space-y-1.5 mb-3">
                              <div className="flex items-start">
                                <MapPin className="w-3.5 h-3.5 mr-1 text-gray-400 flex-shrink-0 mt-0.5" />
                                <span>{r.location}</span>
                              </div>
                              <div className="flex items-start">
                                <span className="text-amber-400 mr-1">⭐</span>
                                <span>{r.rating}</span>
                              </div>
                              <div className="bg-white/5 p-2 rounded-lg mt-2 text-[11px]">
                                <strong className="text-purple-200 block mb-0.5">Must-Try Dish:</strong>
                                <span className="text-gray-300">{r.signature_dishes}</span>
                              </div>
                            </div>
                          </div>

                          <p className="text-[11px] text-gray-400 italic pt-2 border-t border-white/5">
                            "{r.budget_vibe}"
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Local Events Happening This Week */}
                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center space-x-2">
                        <Calendar className="w-5 h-5 text-pink-400" />
                        <h3 className="font-bold text-lg md:text-xl text-white">
                          Local Events & Happenings This Week
                        </h3>
                      </div>
                      <span className="text-xs text-pink-300 bg-pink-500/10 px-2.5 py-1 rounded-full border border-pink-500/30">
                        Live Highlights
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {result.data?.events?.map((ev, i) => (
                        <div
                          key={i}
                          className="bg-black/40 rounded-2xl p-4 border border-pink-500/20 hover:border-pink-500/50 transition-all"
                        >
                          <div className="flex justify-between items-start mb-2">
                            <span className="text-xs bg-pink-500/20 text-pink-300 px-2.5 py-0.5 rounded-full border border-pink-500/30 font-medium">
                              {ev.category}
                            </span>
                            <span className="text-xs bg-white/10 text-white px-2 py-0.5 rounded font-mono">
                              {ev.entry}
                            </span>
                          </div>

                          <h4 className="font-bold text-base text-white mb-2">{ev.title}</h4>

                          <div className="text-xs text-gray-300 space-y-1 mb-3">
                            <div>📅 <strong>When:</strong> {ev.days}</div>
                            <div>📍 <strong>Venue:</strong> {ev.venue}</div>
                          </div>

                          <p className="text-xs text-purple-200 bg-purple-950/40 p-2.5 rounded-xl border border-purple-500/20">
                            ✨ {ev.highlight}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 2: Clean Raw Markdown Document */}
              {activeTab === 'markdown' && (
                <div className="space-y-4">
                  <div className="flex justify-between items-center text-xs text-gray-400">
                    <span>Generated Markdown Document ({result.markdown.length} characters)</span>
                    <button
                      onClick={handleCopyMarkdown}
                      className="text-purple-300 hover:text-white flex items-center font-medium"
                    >
                      <Copy className="w-3.5 h-3.5 mr-1" />
                      {copied ? 'Copied!' : 'Copy Document'}
                    </button>
                  </div>
                  <pre className="p-4 md:p-6 bg-black/80 rounded-xl border border-white/10 font-mono text-xs md:text-sm text-purple-100 whitespace-pre-wrap leading-relaxed select-all overflow-x-auto">
                    {result.markdown}
                  </pre>
                </div>
              )}

              {/* TAB 3: Agent Reasoning & Steps */}
              {activeTab === 'reasoning' && (
                <div className="space-y-4">
                  <p className="text-xs text-gray-400 mb-2">
                    Complete execution trace of autonomous tool invocations and reasoning steps:
                  </p>

                  <div className="space-y-3">
                    {result.steps?.map((step) => (
                      <div
                        key={step.step_id}
                        className="bg-black/40 rounded-xl p-4 border border-purple-500/20 flex flex-col md:flex-row md:items-center justify-between gap-2"
                      >
                        <div className="flex items-start space-x-3">
                          <div className="w-7 h-7 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/40 text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                            {step.step_id}
                          </div>
                          <div>
                            <div className="flex items-center space-x-2">
                              <h4 className="font-bold text-sm text-white">{step.title}</h4>
                              <span className="text-[10px] bg-purple-500/20 text-purple-300 px-2 py-0.5 rounded border border-purple-500/30">
                                {step.tool}
                              </span>
                            </div>
                            <p className="text-xs text-gray-300 mt-1">{step.description}</p>
                          </div>
                        </div>

                        <span className="text-xs text-green-400 font-semibold flex items-center self-end md:self-auto">
                          <Check className="w-3.5 h-3.5 mr-1" />
                          Resolved
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
